SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE LASTNAME='King';
SELECT * FROM EMPLOYEE WHERE FIRSTNAME='Andrew' AND REPORTSTO=NULL;

SELECT * FROM ALBUM ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY ASC;

SELECT * FROM GENRE;
INSERT INTO GENRE VALUES(26, 'FOLK');
INSERT INTO GENRE VALUES(27, 'COUNTRY');

INSERT INTO EMPLOYEE VALUES(9, 'Marcelo', 'Eric', 'IT Staff', 6, NULL, NULL, '924 7 ST NW', 'Lethbridge', 'AB', 'Canada', 'T1H 1y8', '+1 (403) 467-8772', '+1 (403) 467-8772','eric@chinookcorp.com'); 
INSERT INTO EMPLOYEE VALUES(10, 'Marcelo', 'Eric', 'IT Staff', 6, NULL, NULL, '924 7 ST NW', 'Lethbridge', 'AB', 'Canada', 'T1H 1y8', '+1 (403) 467-8772', '+1 (403) 467-8772','eric@chinookcorp.com'); 

SELECT * FROM CUSTOMER;
INSERT INTO CUSTOMER VALUES(60, 'TED', 'THOMAS', NULL, '4, Raj Bhavan Road', 'Bangalore', NULL, 'India', '560001', '+91 080 22289999', NULL, 'ted_thomas@yahoo.in', 3);
INSERT INTO CUSTOMER VALUES(61, 'JOSEPH', 'THOMAS', NULL, '9, Raj Bhavan Road', 'Bangalore', NULL, 'India', '560001', '+91 080 22277111', NULL, 'jo_thomas@yahoo.in', 3);

SELECT * FROM CUSTOMER WHERE FIRSTNAME='Aaron' AND LASTNAME='Mitchell';
UPDATE CUSTOMER SET FIRSTNAME='Robert', LASTNAME='Walter' WHERE FIRSTNAME='Aaron' AND LASTNAME='Mitchell';

SELECT * FROM ARTIST;
SELECT * FROM ARTIST WHERE NAME='Creedence Clearwater Revival';
UPDATE ARTIST SET NAME='CCR' WHERE NAME='Creedence Clearwater Revival';

SELECT * FROM ARTIST WHERE NAME='CCR';

SELECT * FROM INVOICE WHERE BILLINGADDRESS LIKE 'T%';

CREATE OR REPLACE FUNCTION NAME_LENGTH(NAME IN VARCHAR2)
RETURN NUMBER
AS
LEN NUMBER:= 0
BEGIN
LENGTH(NAME)
END NAME_LENGTH;
