-- 2.0 DQL
----2.1 select queries
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE 
  WHERE LASTNAME='King';
SELECT * FROM EMPLOYEE
  WHERE FIRSTNAME='Andrew'
  AND REPORTSTO IS NULL;
  
----2.2 order by 
SELECT * FROM ALBUM ORDER BY TITLE;

SELECT * FROM CUSTOMER ORDER BY CITY ASC;

